/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.util.Calendar;
import javax.swing.JSpinner;
import Logica.Controlador;
import Logica.Genero;
import static java.awt.SystemColor.control;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class AltaGenero extends javax.swing.JInternalFrame {

    
    Controlador control= new Controlador();
    
    public AltaGenero() {
        initComponents();
        this.setTitle("Alta Genero");
        setSize(500, 300);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextNuevoGenero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextPadre = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nuevo Genero:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 110, -1));

        jTextNuevoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNuevoGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNuevoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 130, -1));

        jLabel2.setText("Genero Padre (Opcional):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));

        jTextPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPadreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, -1));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPadreActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
    String genero = jTextNuevoGenero.getText().trim();
    String padre = jTextPadre.getText().trim();
    
    if (genero.isEmpty()) {
        System.out.println("El género no puede estar vacío");
        return; // Salir del método si el género es vacío
    }
    
    if (padre.isEmpty()) {
        padre = "GENERO";
    }
    
    try {
        control.CrearGenero(genero, padre);
        JOptionPane.showMessageDialog(null, "Género agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
    }   
    
    setVisible(false);
}
    {

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextNuevoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNuevoGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNuevoGeneroActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
            setVisible(false);
    }//GEN-LAST:event_jButtonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextNuevoGenero;
    private javax.swing.JTextField jTextPadre;
    // End of variables declaration//GEN-END:variables
}
